#!/bin/bash

echo "Installing Play! Framework 1.2.5.3"
set -e

install-packages unzip wget

echo "Downloading play"
wget http://downloads.typesafe.com/play/1.2.5.3/play-1.2.5.3.zip

echo "Unpacking play"
unzip play-1.2.5.3.zip

cat >> /home/hadoop/.bashrc <<EOF
PATH=\$PATH:($pwd)/play-1.2.5.3/
EOF
